# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 王峰的博客
subtitle: 保持学习
description:
author: 王峰
email: work@wangfeng.pro
language: zh-CN
timezone: Asia/Shanghai
location: 杭州

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.wangfeng.pro
root: /
permalink: :year/:month/:post_title.html
permalink_defaults:
  lang: en
pretty_urls:
#  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: languages
skip_render:
  - README.md
  - '*.html'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
#external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
#highlight:
#  enable: false
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: true    # default false
  custom_css:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 9
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
#skip_render: README.md
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: BlueLake

## 压缩css文件
stylus:
  compress: true

# https://github.com/mythsman/hexo-douban
douban:
  user: wf2311
  builtin: false
  book:
    title: '我的书单'
    quote: '我的豆瓣书单'
  #  movie:
  #    title: '我的电影'
  #    quote: 'This is my movie quote'
  timeout: 20000

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
#    repo: https://github_token@github.com/wf2311/wf2311.github.io.git
    repo: https://github.com/wf2311/wf2311.github.io.git
    branch: master
  - type: git
    repo: https://gitee.com/wf2311/wf2311.gitee.io.git
    branch: master
  - type: git
    repo: https://gitee.com/wf2311/wf2311.git
    branch: master

# https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap
sitemap:
  path: sitemap.xml
  tag: false
  category: false
encrypt:
    enable: true

menu:
  - title: 标签
    url: /tags
    icon: fas fa-tags
  - title: 分类
    url: /categories
    icon: fas fa-bookmark
  - title: 归档
    url: /archives
    icon: fas fa-archive
  - title: 转载
    url: /tags/转载
    icon: fas fa-star
  - title: 友情链接
    url: /friends
    icon: fas fa-address-book
  - title: Wakatime
    url: https://wakatime.wangfeng.pro
    icon: fas fa-bar-chart-o
